// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnAmY01BuB-zJmoM-3so-Yp1XYWsXrSsQ',
    appId: '1:147814267525:web:fdd64b1db6ef47b75dc7ec',
    messagingSenderId: '147814267525',
    projectId: 'obatshop-9ee82',
    authDomain: 'obatshop-9ee82.firebaseapp.com',
    storageBucket: 'obatshop-9ee82.appspot.com',
    measurementId: 'G-MZGZVQ7KSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpFnm6R7Es9HgdQ5Q-qLljOayzywqACVc',
    appId: '1:147814267525:android:c6935bd35bae6a185dc7ec',
    messagingSenderId: '147814267525',
    projectId: 'obatshop-9ee82',
    storageBucket: 'obatshop-9ee82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnbcqerWJMD3OradALJDe31y1H3xqk334',
    appId: '1:147814267525:ios:bf952402e4bf9b705dc7ec',
    messagingSenderId: '147814267525',
    projectId: 'obatshop-9ee82',
    storageBucket: 'obatshop-9ee82.appspot.com',
    iosBundleId: 'com.example.apotek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnbcqerWJMD3OradALJDe31y1H3xqk334',
    appId: '1:147814267525:ios:90e128c8a375c5fb5dc7ec',
    messagingSenderId: '147814267525',
    projectId: 'obatshop-9ee82',
    storageBucket: 'obatshop-9ee82.appspot.com',
    iosBundleId: 'com.example.apotek.RunnerTests',
  );
}
